from django.contrib import admin

from .models import *

admin.site.register(Game)
admin.site.register(Trainer)
admin.site.register(TrainerAttack)
admin.site.register(Species)
admin.site.register(Pokemon)
admin.site.register(Attack)
admin.site.register(SpeciesAttack)
admin.site.register(PokemonAttack)
admin.site.register(Edge)
admin.site.register(TrainerEdge)
admin.site.register(EdgeAttack)
admin.site.register(Feature)
admin.site.register(TrainerFeature)
admin.site.register(FeatureAttack)
admin.site.register(Evolution)
admin.site.register(Item)
admin.site.register(TrainerItem)
admin.site.register(Note)
admin.site.register(DamageBase)
admin.site.register(Nature)
admin.site.register(Type)
admin.site.register(TypeEffectiveness)

admin.site.register(Image)
admin.site.register(Message)
admin.site.register(Background)
admin.site.register(Token)
